source/includes/_static_va_response_code.md
add VA Aggregator Response Codes 226 - Request is rejected (Transaction expiry time exceeds VA expiry time)
=> add response code 226

source/includes/_offline_api.md
change staging url description to `TBD` for all api offline endpoint
based on: https://oyteam.slack.com/archives/G016G7F07A5/p1627381873002800
=> [api offline] tbd staging link for API Offline product

source/includes/_biller_api.md
Fix product id on API Biller PBB products list since it is incorrectly defined
=> [B2X][API Biller] fix product id on API Biller PBB products list

source/includes/_api_multi_account_management.md
change `balances` description to reduce scrolling on get child balance response parameter table.
Before:
=> change balances description on get child balance

source/includes/_disbursement_banks.md
remove maybank syariah from bank codes since it has incorrect bank code (016), should be (947). and is currently not supported by us
=> [Disbursement Bank Codes] remove maybank syariah from bank codes

source/includes/_fund_acceptance.md
[Payment Checkout] Remove due_date field because it is unused and can cause confusion on partner.
By not supplying `due_date`, the value will be the same as expiration
=> [Payment Checkout] Remove due_date field

source/includes/_payment_routing.md, source/includes/static_va.md.erb
Updates payment and inquiry info for BSI VAs, since payments and inquiries involving a BSI VA made using BSI Mobile or Banking Syariah Indonesia Net requires the user to only input the last 12 digits of the va number we sent back (basically remove the 6059 part from the beginning of the va number).
=> Update Payment and Inquiry Information for BSI VAs

.github/workflows/build.yml
Removes `gem update --system` since it has been causing some issues in CI. Context in slack: https://oyteam.slack.com/archives/C01N68XN3K2/p1672034918063539?thread_ts=1671519789.594199&cid=C01N68XN3K2
=> Remove gem update Command from build.yml

README.md, docker-compose.yml
Since it can be difficult to set up the Slate environment locally, this pull request aims to provide a Docker Compose file to make it easy for engineers to develop without the need for manual setup or maintenance of the environment.
=> [Chore] Add docker compose 

source/includes/_api_account_linking.md
[Account Linking] Fix typo in "How we notify linking result" section
=> [Account Linking] Fix typo in "How we notify linking result" section

source/includes/_payment_routing.md
Remove coming soon unique code BCA from `List of Allowed Payment Methods and SOF` section in payment routing.
=> [Payment Routing] Remove Coming Soon Unique Code BCA

source/includes/e_wallet.md.erb
Update ewallet aggre api docsUpdate ewallet aggre api docs. Related to contract changes that move data from Body to Query params.
endpoint impacted:
- http://172.11.25.113:8080/api/e-wallet-aggregator/get-refund?refund_id=15ade525-227f-4e85-be1b-08df930aa935
- http://172.11.25.113:8080/api/e-wallet-aggregator/list-refund?partner_trx_id=test-api-refund-dana-022
related pr:
https://oyteam.slack.com/archives/C01N68XN3K2/p1684915313589329
=> Update ewallet aggre api docs

source/includes/static_va.md.erb
[VA] Add Lifetime Capability and Max Expiration Time Info
=> [VA] Add Lifetime Capability and Max Expiration Time Info

source/includes/_biller_api.md
Add Mocking Response Code for: 
**302 - Customer Id Not Found**
**305 - Bill Not Found Or Already Paid**
Result in Local:
=> [API Biller] Mocking API Biller Error Response Code. (ETA: 2 November 2023)

source/includes/_payment_routing.md
Adds new payment routing callback examples per payment method & update example for VA
=> [Payment Routing] Add Separate Callback Examples per Payment Method for Payment Routing

source/includes/static_va.md.erb
[VA Callback] Add Nullable Info Parameter trx_expiration_date
=> [VA Callback] Add Nullable Info Parameter trx_expiration_date

source/includes/_static_va_response_code.md
Update Response Code Description
=> [VA] Update Response Code Description

source/includes/_fund_disbursement.md
**Summary**: This PR is adjust request params on each language
**Preview**: https://github.com/oyindonesia/external-api-docs/blob/feature/adjust-api-disbursement/source/includes/_fund_disbursement.md
**Related Docs**: https://docs.google.com/document/d/1_5fRTyZXQRiuvI62uhRhefouufxttOfN9jaPSezC7Qk/edit
=> [Disbursement API Documentation] Adjust API Docs for Fund Disbursement

source/includes/static_va.md.erb
Several clients need the ability to deactivate their virtual account numbers via API. Currently, we do not have a dedicated API for this purpose. As an alternative solution, we have been suggesting that clients utilize the API for updating virtual account (VA) information with specific modifications to the request parameters. However, this alternative solution is not explicitly documented, leading to confusion among the integration team and clients about its proper usage.
This PR adds a new section to our documentation, explaining how to deactivate a virtual account number by utilizing the existing API for updating VA information.
=> [VA Aggregator] Add Deactivate VA section

source/includes/_fund_disbursement.md
**Summary**: Currently only successful response that exist in API Docs. This PR is adding failed response for API Disbursement on API Docs. Also adjust some successful response
**Related Docs**: https://docs.google.com/document/d/1_5fRTyZXQRiuvI62uhRhefouufxttOfN9jaPSezC7Qk/edit
=> Feat: Add Sample Response Successful and Failed for Service Disbursement

source/includes/_payment_routing.md
=> [Payment Routing] Clarify Bank Transfer Info for Payment Routing

source/includes/static_va.md.erb
Fixes a note that mentions wrong field to deactivate a VA
Fixes: https://oyteam.slack.com/archives/CHD9AR5FX/p1718945667264229
=> fix: wrong va field to expire VA

source/includes/_fund_disbursement.md
based on project https://linear.app/oy-indonesia/project/deprecate-disbursement-v1-66930f4d33ca
Deprecate Disbursement V1 & Implement New Mocking Service
=> [API Disbursement][Mock] update mock data reference

docker-compose.yml
Making the local image's name fixed
=> [Fix] Docker image not found when running locally

source/includes/_api_get_transaction_summary
=> feat: add API get transaction Summary

source/includes/_payment_routing.md
Add qris deactivation documentation for payment routing section
Preview:
=> [Acceptance][Qris] Add deactivate payment routing documentation

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/dev_deploy.yml
Update actions/cache to v4 in workflow files. Caused by deprecation of action/cache-v2. 
https://github.com/actions/cache/discussions/1510
=> update actions/cache to v4 in workflow files

source/includes/static_va.md.erb
Remove `For all available banks, there is no minimum expiration time.` as it's no longer relevant
=> [VA] Remove "For all available banks, there is no minimum expiration time."
