oyindonesia/external-api-docs

source/index.html.md

Added base url info to static va generator

Added base url info

---

source/index.html.md

Revamp documentation static va generator

Improve static VA documentation

---

source/includes/_fund_disbursement.md

[Update Balance] Update balance docs

---

source/includes/_disbursement_banks.md

remove-bank-bengkulu

---

source/includes/_fund_acceptance.md

[Improvement] Improve POSTMAN general wording

---

source/includes/_fund_acceptance.md

Reverts oyindonesia/external-api-docs#18

Revert "[Improvement] Improve POSTMAN general wording"

---

source/includes/_fund_acceptance.md

[Improvement] Checkout Delete

---

source/includes/_fund_acceptance.md

[Bugfix] Change Labelling

---

source/includes/_fund_acceptance.md

add invoice param

---

source/includes/_fund_acceptance.md

Checkout callback

---

source/includes/_fund_acceptance.md

Change AK 47 to Semmen Gresik

---

source/includes/_fund_acceptance.md

Change Success To Status

---

source/includes/_fund_disbursement.md

Modify curl header request for API inquiry

Modify curl header request

---

source/includes/_disbursement_banks.md
source/includes/_fund_disbursement.md

Add Bank Code and Fix Header in CURL request
Screenshot:

Add bank code and modify header

---

source/includes/_fund_acceptance.md

Change Charge failed to failed

---

source/includes/_fund_acceptance.md

mapping sttatus

---

source/includes/_fund_acceptance.md

Staging api mapping

---

source/includes/_authentication.md
source/includes/_fund_disbursement.md

Remove sandbox.oyindonesia.com as BASE_URL and add staging info for API Disburse

Remove sandbox.oyindonesia.com as BASE_URL and add staging info for API Disburse

---

source/includes/_account_inquiry.md
source/includes/_account_inquiry_response_code.md
source/index.html.md.erb

Add new API docs for Inquiry

---

source/includes/_account_inquiry.md

Change timestamp API Inquiry to UTC. To follow the API disburse timestamp

Change timestamp API Inquiry to UTC

---

source/includes/_fund_disbursement.md

- Update wording to lessen confusion on update & delete scheduled disburse

Update wording for update & delete scheduled disbursement

---

source/includes/_fund_disbursement.md

remove api inquiry

---

source/includes/_account_inquiry.md
source/includes/_account_inquiry_response_code.md

Add docs for API Inquiry payment feature

Add docs for API Inquiry payment feature

---

source/includes/_account_inquiry.md

Add more info related to account inquiry status transition

Add more info related to account inquiry status transition

---

source/includes/_fund_acceptance.md

Tidy up payment checkout callback CURL

Tidy up payment checkout callback CURL

---

source/includes/_account_inquiry.md

Add missing quote on account inquiry response

Add missing quote on account inquiry response

---

source/includes/_fund_acceptance.md

Change Payment Checkout Jokowi Name to Budi

---

source/includes/_offline_api.md

Add missing response code (990) invalid object or parameter to api docs

[B2X API Offline] Add missing response code (990)

---

source/includes/_offline_api.md

Fix response code description of 990 status to 'Parameter / object is not valid'

[B2X API Offline] Fix 990 Response code description

---

source/includes/_offline_api.md

split response code of API Offline for better readability

[API OFFLINE] split response codes for better readability

---

.github/ISSUE_TEMPLATE/bug.md
.github/workflows/build.yml
.github/workflows/dev_deploy.yml
.github/workflows/publish.yml
CHANGELOG.md
Dockerfile
Gemfile
Gemfile.lock
README.md
Vagrantfile
slate.sh
source/javascripts/app/_copy.js
source/javascripts/app/_lang.js
source/javascripts/lib/_lunr.js

Merge upsteam

---

source/includes/_fund_acceptance.md

fix payment checkout

---

source/includes/_api_based_transactions_data.md

Add new status code for transaction data

---

source/includes/_api_based_transactions_data.md

Change staging endpoint to upcoming

Change stg endpoint to upcoming

---

source/includes/_api_based_transactions_data.md

Improve request and response fot init and get account statement

Fix several curl endpoint request and response

---

source/includes/_account_inquiry.md
source/includes/_api_based_transactions_data.md
source/includes/_fund_acceptance.md
source/includes/_fund_disbursement.md
source/includes/_offline_api.md
source/includes/static_va.md.erb
source/stylesheets/screen.css.scss

This task is about fixing search bar size, unhide scrollbar from codeblock, and add header in every code example.
You can check in https://oy-api-demo.web.app/

[HOTFIX] Fix Layout

---

source/includes/_account_inquiry.md

This task about removing header codeblock ("Below code .....") in API inquiry document
You can check in https://oy-api-demo.web.app/

[Document] remove header codeblock API inquirty

---

source/includes/_docs_changelog.md
source/index.html.md.erb

Add document section called "docs changelog"
You can check in https://oy-api-demo.web.app/

[Document] Add docs changelog section

---

source/layouts/layout.erb

Change link to dashboard in header
You can check in https://oy-api-demo.web.app/

[HOTFIX] change link dashboard in header

---

source/includes/_api_based_transactions_data.md
source/includes/_fund_acceptance.md
source/includes/_fund_disbursement.md
source/includes/static_va.md.erb
source/javascripts/all_nosearch.js
source/javascripts/app/_toc.js
source/layouts/layout.erb
source/stylesheets/screen.css.scss

- Add new documentation for VA aggregator, Transaction Data, and Fund Acceptance (Payment Checkout)
- Fixing dropdown list h3 (auto close dropdown, just open specific list h3 that corresponding with page)
Before
After
You can check in https://oy-api-demo.web.app

Add new documentation and Fixing dropdown TOC list h3

---

source/includes/_fund_acceptance.md

Add transaction due date and email in API Docs Fund Acceptance

[Feature] Add transaction due date & edit email parameters in Fund Acceptance

---

source/includes/static_va.md.erb

Add Bank Code BTPN

---

source/includes/_disbursement_banks.md

add missing BPR KS bank code by request from thread : https://oyteam.slack.com/archives/CHD9AR5FX/p1630895037329200

Add BPR KS bank code

---

source/includes/_disbursement_banks.md

Delete BNIS, BRIS, and BSM bank codes and add BSI bank code according to [this thread](https://oyteam.slack.com/archives/CHD9AR5FX/p1631606016116900).

Add BSI Bank Code

---

source/includes/e_wallet.md.erb

EWallet Status code

---

source/includes/e_wallet.md.erb

Remove DANA env param from ewallet docs and add ref num param in response
Also fix double email error

Remove DANA env param from ewallet docs and add ref num

---

source/includes/_fund_acceptance.md

Add copy for iframe

---

source/includes/_payment_routing.md
source/index.html.md.erb

Add API Docs Payment Routing

---

source/includes/_fund_disbursement.md

add check status sla

---

source/includes/_disbursement_banks.md

Add Shopeepay to Disbursement Bank Codes

---

source/includes/_biller_api.md

Implement api documentation for upcoming product API Biller.
https://oyteam.quip.com/xqbyAeTprmoq/Design-Document-Biller-API

[B2X][API Biller] Initiate api biller api docs

---

source/index.html.md.erb

add missing includes for api biller to index.html.md.erb

[B2X][API Biller] add missing includes to index.html

---

source/includes/_payment_routing.md

updates in payment routing api docs 

---

.github/workflows/deploy.yml
source/includes/e_wallet.md.erb

Test github action and add some example to test it

Add fix to deployment branches and add test example

---

source/includes/e_wallet.md.erb

Title, might revert it if example need to be similar in value with other example

Change ewallet example to test auto deployment

---

source/includes/_send_whatsapp.md
source/index.html.md.erb

Add new Whatsapp API Section

---

source/includes/_fund_acceptance.md

Remove Step in API Docs

---

source/includes/_offline_api.md

Update api offline response and request according to the new docs

modify api offline docs

---

source/includes/_api_multi_account_management.md

change v2 to V1 in endpoint get child balance MAM API

---

source/includes/static_va.md.erb

Update BNI - Open Amount

---

source/includes/static_va.md.erb

https://oyteam.slack.com/archives/CHD9AR5FX/p1646112144770339

Fix bank code and status VA

---

source/includes/static_va.md.erb

fix link API Docs VA

---

source/includes/_fund_acceptance.md

Add param related to MAM Acceptance

---

source/includes/_biller_api.md

fix wrong title name and error when showing table in markdown

[API BILLER] fix error in table and wrong title name

---

source/includes/_biller_api.md

[API BILLER]fix get products list description

---

source/includes/_payment_routing.md

Rename qr_url to qris_url on payment routing

Rename qr_url to qris_url on payment routing

---

source/includes/_send_whatsapp.md

Fix add callback to whatsapp api section

---

source/includes/_send_whatsapp.md

move json request body

---

source/includes/_biller_api.md

change api biller pending RC state to non final because its not a final state

[B2X][API Biller] change api biller rc 400 pending to non final state

---

source/includes/_static_va_response_code.md

Add description for 213 error on static va

Add description for 213 status code on static va

---

source/includes/_biller_api.md

-  223 Responsce Code for Biller Products

[Add] 223 Responsce Code for Biller Products

---

source/includes/_biller_api.md
source/includes/_disbursement_banks.md
source/includes/_disbursement_response_code.md

change seabank name, delete rc 225 api disburse, add 5 new rc failed api biller

---

source/includes/_payment_routing.md

- Add missing field `status` on response parameters
- Reorder `qris_urls` so it's near `payment_info` field instead of `payment_routing`
- Add callback body info

[Payment Routing] Add missing field and callback body

---

source/includes/static_va.md.erb

Add VA BSI in list of bank codes

Add VA BSI in bank code

---

source/includes/_biller_api.md

Adjust request/response of api biller based on this issue: https://oyteam.slack.com/archives/CHD9AR5FX/p1664183217079429

[API Biller] adjust json request/response for api biller docs

---

source/includes/_payment_routing.md

[Payment Routing] Update docs to reflect current production
- Fix typo `partner_tx_id` -> `partner_trx_id`
- Add `receive_amount` on callback response
- Remove `receive_amount` on check-status
- Add `request_amount` and `received_amount` on check-status

[Payment Routing] Update docs to reflect current production

---

source/includes/static_va.md.erb

Adds bank codes for Maybank, Hana, Danamon for VA aggregator API docs.

Add bank codes for Maybank, Hana, Danamon

---

source/includes/_fund_disbursement.md

Add redirect URL to product docs for resend callback API disburse in https://docs.oyindonesia.com/

[Docs] Add redirect url to product docs for resend callback api disburse

---

source/includes/_biller_api.md

Because admin_fee is now in response, we need to add it in api docs.

[B2X][API Biller] add admin fee in json responses

---

source/includes/_payment_routing.md
source/includes/static_va.md.erb

Add method details in callback part to help user knows what we use

Add method details in acceptance docs

---

source/includes/_biller_api.md

[B2x][Biller] add missing rc 307 for api biller

---

source/includes/_api_account_receivable.md

add api docs for api ar

---

source/includes/_static_va_response_code.md
source/includes/static_va.md.erb

Add API Docs for Customized VA:

add API docs for custom VA

---

source/includes/_api_account_receivable.md

Add example code for api AR

---

source/includes/_fund_acceptance.md

Adds a new column ("Required") for Payment Link Creation docs.

Add "Required" Column for Payment Link Create RQ docs

---

source/includes/_fund_acceptance.md

Updates PL min amount from 15k to 10k (IDR).

Update Minimal Amount Info for Payment Link Creation

---

source/includes/_payment_routing.md

Adds info regarding BSI VA creation for payment routing.

Additional BSI VA Info - Payment Routing

---

source/includes/_payment_routing.md

Updates information regarding QRIS transactions, especially for Payment Routing.

Update QRIS Trx Information [ETA 2 November 2022]

---

source/includes/_payment_routing.md

Update the payment routing details by including the following information:
- Add a more detailed description of the transaction expiration time, including the default time and allowed input values
- Provide an explanation for the success_redirect_url field
------
------
------

Update API payment routing

---

source/includes/_payment_routing.md

[API Docs][Payment Routing] Add ewallet_url description

---

source/includes/_fund_disbursement.md

- Add new response code on Transaction Status: API Create Disbursement docs

feat: update docs transaction status API Create Disbursement

---

source/includes/_payment_routing.md

[Ready to release][Api docs] add docs for cc/dc payment routing

---

source/includes/_payment_routing.md

Edit payment routing API docs due to addition of bank transfer (unique code BCA) payment method.

Payment Routing API Docs for Unique Code BCA

---

source/includes/_payment_routing.md

add bank code parameter on payment routing create response

[Payment Routing] Add Bank Code Parameter on Payment Routing Create Response

---

source/includes/_payment_routing.md

[Payment Routing] Move info about auto generated field from partner_user_id to partner_trx_id

[Payment Routing] Move info about auto generated field from partner_user_id to partner_trx_id

---

source/includes/_payment_routing.md

[Payment Routing] Add info about generated partner_user_id

[Payment Routing] Add info about generated partner_user_id

---

source/includes/_api_account_linking.md

[Account Linking] Fix typo partnerUserId

[Account Linking] Fix typo partnerUserId

---

source/includes/_fund_acceptance.md

Adjust Fund Acceptance Section Due to Unique Code BCA Addition

Adjust Fund Acceptance Section Due to Unique Code BCA Addition

---

source/includes/_biller_api.md

add missing object for biller docs:
- for callback add note
- for check status add tx_status_description

[Disbursement][Biller] add missing object for biller docs

---

source/includes/_biller_api.md

add amount and additional_data to inquiry request objects

[Disbursement][Biller API] add amount and additional_data to inquiry request

---

source/includes/_fund_acceptance.md
source/includes/_payment_routing.md

Adds new param (payment_reference_number or RRN) & new condition/warning for payment link and payment routing check status docs

[Payment Link] [Payment Routing] Adjust Payment Link (Fund Acceptance) and Payment Routing Check Status Docs

---

source/includes/_transaction_detail.md
source/index.html.md.erb

Add new API: Transaction Detail API.
For more context, please refer to [this document](https://docs.google.com/document/d/1gEvsc0jNnw7gSrYh9x4jkSPWvKBmfyV-sDzM0oarZck/edit).

Write request response docs

---

source/includes/_biller_api.md

Fix request api biller status from body to url params

[Disbursement][API Biller] fix request api biller status

---

source/includes/_fund_acceptance.md
source/includes/_payment_routing.md

[Payment Routing] [Payment Checkout] Update Info for Payment Routing and Link Check Status + Callback Params

---

source/includes/_payment_routing.md

[Payment Routing] Add Delayed Settlement Callback Info for Payment Routing

---

source/includes/_transaction_detail.md

staging for api transaction detail

---

source/includes/_static_va_response_code.md

Add RC va aggregator duplicate partner tx id

[External api docs] Add RC va aggregator duplicate partner tx id

---

source/includes/_payment_routing.md

[Payment Routing] Add payment routing response codes

[Payment Routing] Add payment routing response codes

---

source/includes/_payment_routing.md

[Payment Routing] Change wording on need_frontend: false to payment aggregator

[Payment Routing] Change wording on need_frontend: false to payment aggregator

---

source/includes/static_va.md.erb

[VA Aggregator] Change Character Limit on Email Parameter VA Aggregator

---

source/includes/_payment_routing.md

[Payment Routing] Add unique code addition or subtraction info

[Payment Routing] Add unique code addition or subtraction info

---

source/includes/_payment_routing.md

Fix table for HTTP status code payment routing

Fix table for HTTP status code payment routing

---

source/includes/_offline_api.md

Add notes to api offline request payload

[Offline] Add notes

---

source/includes/_static_va_response_code.md

Update VA Aggregator response codes related with this project: https://oyteam.slack.com/archives/C01N68XN3K2/p1687516464149559

[VA Aggregator] Update Response Code

---

source/includes/_fund_acceptance.md
source/includes/_payment_routing.md

Fix table formatting

---

source/includes/_static_va_response_code.md

Add some response codes on VA Aggregator API docs
HTTP Status Code | Description
---------- | -------
403 | Forbidden (IP address is not whitelisted or request is deemed suspicious e.g SQL injection or XSS)
404 | Not Found (wrong URL)
429 | Request Rejected (Too Many Request to specific endpoint)
500 | Internal Server Error (OY! system encountered unknown error)
503 | Service Unavailable (OY! system is unable to process the request temporarily)
504 | Gateway Timeout (OY! system took too long processing the request and was unable to respond in time)

[VA Aggregator] Add HTML Response Codes

---

source/includes/_e_wallet.md
source/includes/e_wallet.md.erb

Add generic error response to ewallet error code
Preview in intellij:

[EWallet Aggregator] Add generic error code in ewallet aggregator page

---

source/includes/_fund_disbursement.md

Adding new response code 504 on Transaction Status: API Create Disbursement

---

source/includes/_payment_routing.md

[Payment Routing] Use underscore for status

[Payment Routing] Use underscore for status

---

source/includes/static_va.md.erb

[VA] Add Info Supported Bank Code (BRI and CIMB) Customized VA

[VA] Add Info Supported Bank Code Customized VA

---

source/includes/_biller_api.md

Convert Api Biller Additional Data Format from Object To Json String.
Result in Local:

[API Biller] API Biller Additional Data Format. (ETA: 23 November 2023)

---

source/includes/_payment_routing.md

[Payment Routing] Add payment_method and sender_bank field
Changes
| Section | Screenshot |
|---------|-------------|
| Check Status response table | <img width="1439" alt="Screen Shot 2023-11-23 at 15 11 51" src="https://github.com/oyindonesia/external-api-docs/assets/5603786/5f8741bd-0a9a-48ae-abea-a1e78d2f91bc"> |
| Check Status response example | <img width="1440" alt="Screen Shot 2023-11-23 at 15 09 49" src="https://github.com/oyindonesia/external-api-docs/assets/5603786/0946caee-901f-4e6c-8d8c-246c09167cea"> |
| Callback response table | <img width="1440" alt="Screen Shot 2023-11-23 at 15 12 52" src="https://github.com/oyindonesia/external-api-docs/assets/5603786/21528a4b-560c-4529-be26-4c407391b40d"> |
| Callback response example | <img width="1440" alt="Screen Shot 2023-11-23 at …

[Payment Routing] Add payment_method and sender_bank field

---

source/includes/_timeout.md
source/index.html.md.erb

https://oyteam.slack.com/archives/CHD9AR5FX/p1701240619870669?thread_ts=1700800512.352029&cid=CHD9AR5FX

Add timeout section

---

source/includes/static_va.md.erb

[VA] Add Info Parameter partner_trx_id in callback VA is nullable

[VA] Add Info Parameter partner_trx_id in callback VA is nullable

---

source/includes/_timeout.md

Added other API timeout info
1.  VA Aggregator
2. Fund Acceptance
3. Payment Routing
4. Account Linking

enrich api docs timeout info

---

source/includes/_disbursement_banks.md

Update bank code 501 name to `BCA Digital (blu)`

[Disbursement Bank Codes] update 501 bank name to bca digital blu

---

source/includes/_static_va_response_code.md

Add additional response codes description for response code `990` to elaborate the cause of error when a parameter is invalid/required. 
Related:
- https://github.com/oyindonesia/javarepo/pull/19989/files

[VA] Add invalid param response code description

---

source/includes/_fund_disbursement.md

**Summary:** This PR is enhance section mock data in demo environment for disbursment
**Preview:** https://github.com/oyindonesia/external-api-docs/blob/feature/adjust-api-disbursement/source/includes/_fund_disbursement.md
**Related** Docs: https://docs.google.com/document/d/1_5fRTyZXQRiuvI62uhRhefouufxttOfN9jaPSezC7Qk/edit

[Disbursement API Documentation]  add mock data in demo env disbursement

---

source/includes/static_va.md.erb

https://linear.app/oy-indonesia/issue/OYACC-881/%5Bangga%5D%5Bva%5D-update-api-docs-response-object

[Api Docs] Adjust va list trx doc

---

source/includes/static_va.md.erb

[VA Aggregator] Get tx list: Clarify VA ID type

---

Dockerfile
docker-compose.yml

Fixes all issue when serving docs locally via docker-compose
- Ruby gem pinning
- Undefined constant Rouge::Theme::Oy

Fix local serve using docker-compose

---

source/includes/_fund_disbursement.md

fix json showing after description on `Mock Data in Demo Environment`

[API Disburse] move json to first thing after title

---

source/includes/_fund_disbursement.md

based on issue: https://oyteam.slack.com/archives/CHD9AR5FX/p1721719496122479

[Fund Disbursement] fix callback response on tx_status_description

---

source/includes/_disbursement_banks.md

Update bank list base on this [file](https://docs.google.com/spreadsheets/d/1nMK6E0Abt-HBZSH1Zh18T_9aoz3po8fx/edit?pli=1&gid=1533500355#gid=1533500355)

feat: Update bank codes list

---

source/includes/_disbursement_banks.md

Bank Jateng Syariah should be 725 (already added)

Update disbursement bank codes list

---

source/includes/static_va.md.erb

Add info Default Date Limit Filter last 3 months API Get List of Transaction for VA

[VA Aggregator] Add info Default Date Limit Filter API Get List of Transaction for VA

---

source/includes/_disbursement_banks.md

change bank names:
- 494
- 553
- 118
- 118S

[Disbursement Banks][29 Aug 2024] change bank names

---

source/includes/_api_account_receivable.md

Change incorrect docs and update docs to match with current API AR implementation

Update API AR Docs with new response

---

source/includes/_payment_routing.md

[Payment Routing] Add info for Payment Failed

[Payment Routing] Add info for Payment Failed

---

source/includes/_disbursement_banks.md

rename bank name btpn to smbc for bank code 213

rename btpn to smbc

---

source/includes/_payment_routing.md
source/includes/_qris_aggregator.md
source/index.html.md.erb

Screenshots: https://oyteam.slack.com/archives/C02C7DYJEAC/p1747639531146379?thread_ts=1745815723.030139&cid=C02C7DYJEAC

[QRIS Aggregator] Add QRIS Aggregator Section

---

source/includes/_payment_routing.md

Update bank list allowed in payment routing

---

source/includes/_account_inquiry_response_code.md

Add new Response Code 203 - User Config is not valid in API Account Inquiry.

[Account Inquiry] Add RC 203 - User Config is not valid

---

source/includes/_postman.md

feat: remove getting started postman

---

source/includes/static_va.md.erb

feat: Add info created VA list are limited within last updated 3 months
